### ISSUE TITLE
error executing 3.len.py

### ISSUE THREAD

**Issue by vsbrt** [vsbrt/python-beginners-excersises#1]
_following is the error in the execution window:_

**Traceback (most recent call last):
  File "C:\Python27\python_examples\solutions\3.len.py", line 1, in <module>
    ip = input("Enter a string: ")
  File "<string>", line 1, in <module>
NameError: name 'hhh' is not defined**

**Comment by vsbrt** [comment]
program still under initials stages

**Comment by vsbrt** [comment]
error fixed
