### ISSUE TITLE
6.Sum_pro.py not working

### ISSUE THREAD

**Issue by vsbrt** [vsbrt/python-beginners-excersises#7]
no input  or output on the screen

**Comment by vsbrt** [comment]
code working for fixed input parameters

**Comment by vsbrt** [comment]
worked out with the issue hence closing it

**Comment by vsbrt** [comment]
issue still not resolved. following error was thrown out upon execution:

C:\Python27\python_examples\solutions>6.sum_pro.py
  File "C:\Python27\python_examples\solutions\6.sum_pro.py", line 39
    print(sum(input_string))
                           ^
IndentationError: unindent does not match any outer indentation level

C:\Python27\python_examples\solutions>

**Comment by vsbrt** [comment]
updated the program

**Comment by vsbrt** [comment]
issue still not resolved. following error was thrown out upon execution:

C:\Python27\python_examples\solutions>6.sum_pro.py
enter numbers separated by comas:1, 8, 2
Traceback (most recent call last):
  File "C:\Python27\python_examples\solutions\6.sum_pro.py", line 39, in <module>
    print(sum(input_string))
  File "C:\Python27\python_examples\solutions\6.sum_pro.py", line 26, in sum
    total += number
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

C:\Python27\python_examples\solutions>

**Comment by vsbrt** [comment]
small error due to mis-aligned spaces. fixed now

**Comment by vsbrt** [comment]
finally fixed with all errors
