### ISSUE TITLE
program 7

### ISSUE THREAD

**Issue by vsbrt** [vsbrt/python-beginners-excersises#9]
need to start working on program 7

**Comment by vsbrt** [comment]
started work on program.

**Comment by vsbrt** [comment]
giving out errors on execution

following is the error:

C:\Python27\python_examples\solutions>7.reverse.py
Enter the string to reverse
ravi
Traceback (most recent call last):
  File "C:\Python27\python_examples\solutions\7.reverse.py", line 14, in <module>
    reverse_strin = input()
  File "<string>", line 1, in <module>
NameError: name 'ravi' is not defined

C:\Python27\python_examples\solutions>

**Comment by vsbrt** [comment]
issue resolved and program is in final stage
